import { ref, computed } from 'vue'

const currentLanguage = ref(localStorage.getItem('language') || 'en')

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    myBookings: 'My Bookings',
    bookingRequests: 'Booking Requests',
    myListings: 'My Listings',
    addListing: 'Add Listing',
    profile: 'Profile',
    users: 'Users',
    reports: 'Reports',
    logout: 'Logout',
    
    // Welcome Page
    welcomeTitle: 'Rent Houses and Cars – Safely',
    welcomeSubtitle: 'Connect with trusted owners. Every listing is verified for your safety.',
    iWantToRent: 'I Want to Rent',
    iWantToList: 'I Want to List',
    alreadyHaveAccount: 'Already have an account?',
    login: 'Log in',
    signup: 'Sign up',
    forRenters: 'For Renters',
    forOwners: 'For Owners',
    howItWorks: 'How It Works',
    verifiedListings: 'Verified listings',
    transparentPricing: 'Transparent pricing',
    easyBooking: 'Easy booking',
    secureTransactions: 'Secure transactions',
    earnFromAssets: 'Earn from assets',
    simpleListing: 'Simple listing',
    adminVerification: 'Admin verification',
    manageListings: 'Manage listings',
    browseList: 'Browse/list',
    bookSafely: 'Book safely',
    
    // Auth & Signup
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    phone: 'Phone Number',
    dontHaveAccount: "Don't have an account?",
    loggingIn: 'Logging in...',
    creatingAccount: 'Creating account...',
    iWantTo: 'I want to',
    rent: 'Rent (Renter)',
    listAssets: 'List my assets (Owner)',
    verificationInfo: 'Verification Information',
    verificationDesc: 'For safety and security, all users must provide ID verification.',
    nationalId: 'National ID or Passport Number',
    upiId: 'UPI ID / Bank Account (for receiving payments)',
    iAgreeToThe: 'I have read and agree to the',
    termsAndConditions: 'Terms and Conditions',
    iAccept: 'I Accept',
    minimumChars: 'Minimum 6 characters',
    
    // Dashboard
    welcome: 'Welcome',
    browseListings: 'Browse Listings',
    browseAvailableListings: 'Browse available listings below',
    manageYourListings: 'Manage your listings below',
    noListingsFound: 'No listings found matching your criteria.',
    noListingsYet: 'You have no listings yet.',
    addFirstListing: 'Add Your First Listing',
    
    // Common
    search: 'Search',
    type: 'Type',
    all: 'All',
    houses: 'Houses',
    cars: 'Cars',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    price: 'Price',
    location: 'Location',
    status: 'Status',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    submit: 'Submit',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    approve: 'Approve',
    reject: 'Reject',
    save: 'Save',
    back: 'Back',
    perNight: 'night',
    perDay: 'day',
    description: 'Description',
    amenities: 'Amenities',
    features: 'Features',
    rules: 'Rules',
    ownerContact: 'Owner Contact',
    bookThis: 'Book this',
    startDate: 'Start Date',
    endDate: 'End Date',
    gender: 'Gender',
    maritalStatus: 'Marital Status',
    numberOfChildren: 'Number of Children',
    total: 'Total',
    sendBookingRequest: 'Send Booking Request',
    listingNotFound: 'Listing not found',
    backToListings: 'Back to listings',
    
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    pendingReviews: 'Pending Reviews',
    verificationInfo: 'Verification Info',
    idNumber: 'ID Number',
    upiId: 'UPI ID',
    approveListing: 'Approve Listing',
    rejectListing: 'Reject Listing',
    noPendingListings: 'No pending listings.',
    noApprovedListings: 'No approved listings.',
    noRejectedListings: 'No rejected listings.',
    owner: 'Owner',
    submitted: 'Submitted',
    pendingReview: 'Pending Review',
    confirmReject: 'Confirm Reject',
    rejectionReason: 'Rejection reason',
    
    // Alerts/Notifications
    areYouSure: 'Are you sure?',
    deleteListingConfirm: 'Are you sure you want to delete this listing?',
    cancelBookingConfirm: 'Are you sure you want to cancel this booking?',
    blockUserConfirm: 'Block this user? They will need to contact admin to regain access.',
    unblockUserConfirm: 'Unblock this user? They will regain full access.',
    approveListingConfirm: 'Are you sure you want to approve this listing?',
    approveBookingConfirm: 'Approve this booking request?',
    rejectReasonPrompt: 'Please provide a reason for rejection:',
    rejectReasonRequired: 'Please provide a reason for rejection',
    emailAlreadyExists: 'Email already exists',
    invalidCredentials: 'Invalid email or password',
    accountBlocked: 'Your account has been blocked. Please contact admin.',
    
    // Add Listing Form
    addNewListing: 'Add New Listing',
    propertyType: 'Property Type',
    house: 'House',
    car: 'Car',
    title: 'Title',
    titlePlaceholder: 'e.g., Cozy 2-bedroom apartment in Kigali',
    descriptionPlaceholder: 'Describe your property...',
    locationPlaceholder: 'City, District',
    pricePerNight: 'Price per night/day',
    rentalPeriod: 'Rental Period',
    perDayOption: 'Per Day',
    perMonthOption: 'Per Month',
    perYearOption: 'Per Year',
    selectRentalPeriod: 'Select the minimum rental period for your property',
    photoUrl: 'Photo URL',
    photoUrlPlaceholder: 'https://example.com/photo.jpg',
    orUploadPhotos: 'Or Upload Photos',
    uploadPhotos: 'Upload up to 5 photos of your property',
    rulesPlaceholder: 'e.g., No smoking, No pets...',
    verificationInfoDesc: 'This information is only visible to administrators for verification purposes.',
    idNumberPlaceholder: 'Your ID number',
    upiIdPlaceholder: 'Your UPI ID',
    agreeToTermsText: 'I agree to the Terms and Conditions and confirm that all information provided is accurate. I understand that false information may result in listing rejection and account suspension.',
    submitting: 'Submitting...',
    submitForReview: 'Submit for Review',
    required: 'required',
    
    // Admin Users Table
    userManagement: 'User Management',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    blockedUsers: 'Blocked Users',
    name: 'Name',
    role: 'Role',
    phone: 'Phone',
    actions: 'Actions',
    active: 'Active',
    blocked: 'Blocked',
    block: 'Block',
    unblock: 'Unblock',
    admin: 'Admin',
    
    // User Profile
    myProfile: 'My Profile',
    uploadProfilePicture: 'Upload Profile Picture',
    removeProfilePicture: 'Remove Profile Picture',
    basicInformation: 'Basic Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    changePassword: 'Change Password',
    leaveBlankPassword: 'Leave blank if you don\'t want to change password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updating: 'Updating...',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully!',
    removeProfilePictureConfirm: 'Are you sure you want to remove your profile picture?',
    
    // Admin Reports
    bookingReports: 'Booking Reports',
    totalBookings: 'Total Bookings',
    totalRevenue: 'Total Revenue',
    listing: 'Listing',
    renter: 'Renter',
    dates: 'Dates',
    amount: 'Amount',
  },
  
  rw: {
    // Navigation
    dashboard: 'Ibikubiyemo',
    myBookings: 'Aho Natumije',
    bookingRequests: 'Abasaba Gutuma',
    myListings: 'Ibyo Nanditse',
    addListing: 'Andika Ikintu',
    profile: 'Umwirondoro',
    users: 'Abakoresha',
    reports: 'Raporo',
    logout: 'Sohoka',
    
    // Welcome Page
    welcomeTitle: 'Gukodesha Amazu n\'Imodoka – Mu Mutekano',
    welcomeSubtitle: 'Huza n\'abanyir\'ubwite bizewe. Buri kintu cyemejwe ku mutekano wawe.',
    iWantToRent: 'Ndashaka Gukodesha',
    iWantToList: 'Ndashaka Kwandika',
    alreadyHaveAccount: 'Usanzwe ufite konti?',
    login: 'Injira',
    signup: 'Iyandikishe',
    signUp: 'Iyandikishe',
    forRenters: 'Ku bakodesha',
    forOwners: 'Ku banyir\'ubwite',
    howItWorks: 'Uko Bikora',
    verifiedListings: 'Ibintu byemejwe',
    transparentPricing: 'Ibiciro bisobanutse',
    easyBooking: 'Gutuma byoroshye',
    secureTransactions: 'Ibikorwa byizewe',
    earnFromAssets: 'Injiza mu mitungo',
    simpleListing: 'Kwandika byoroshye',
    adminVerification: 'Kwemeza kw\'umuyobozi',
    manageListings: 'Gucunga ibyo wanditse',
    browseList: 'Shakisha/andika',
    bookSafely: 'Tuma mu mutekano',
    
    // Auth & Signup
    email: 'Imeri',
    password: 'Ijambo ry\'ibanga',
    name: 'Amazina yose',
    phone: 'Nimero ya telefoni',
    dontHaveAccount: 'Nta konti ufite?',
    loggingIn: 'Urimo kwinjira...',
    creatingAccount: 'Urimo gukora konti...',
    iWantTo: 'Ndashaka',
    rent: 'Gukodesha (Uwakodesha)',
    listAssets: 'Kwandika umutungo wanjye (Umunyir\'ubwite)',
    verificationInfo: 'Amakuru yo Kwemeza',
    verificationDesc: 'Ku mutekano, abakoresha bose bagomba gutanga indangamuntu.',
    nationalId: 'Indangamuntu cyangwa Pasiporo',
    upiId: 'UPI ID / Konti ya Banki (kugirango ubone amafaranga)',
    iAgreeToThe: 'Nasomye kandi nemera',
    termsAndConditions: 'Amabwiriza n\'Amategeko',
    iAccept: 'Ndabyemera',
    minimumChars: 'Nibura inyuguti 6',
    
    // Dashboard
    welcome: 'Murakaza neza',
    browseListings: 'Shakisha Ibintu',
    browseAvailableListings: 'Shakisha ibintu bihari hano hasi',
    manageYourListings: 'Gucunga ibyo wanditse hano hasi',
    noListingsFound: 'Nta kintu cyabonetse.',
    noListingsYet: 'Ntacyo wanditse.',
    addFirstListing: 'Andika Ikintu Cyawe cya Mbere',
    
    // Common
    search: 'Shakisha',
    type: 'Ubwoko',
    all: 'Byose',
    houses: 'Amazu',
    cars: 'Imodoka',
    minPrice: 'Igiciro cyo hasi',
    maxPrice: 'Igiciro cyo hejuru',
    price: 'Igiciro',
    location: 'Ahantu',
    status: 'Uko bimeze',
    pending: 'Bitegereje',
    approved: 'Byemewe',
    rejected: 'Byanze',
    confirmed: 'Byemejwe',
    cancelled: 'Byahagaritswe',
    submit: 'Ohereza',
    cancel: 'Hagarika',
    edit: 'Hindura',
    delete: 'Siba',
    approve: 'Emeza',
    reject: 'Anga',
    save: 'Bika',
    back: 'Subira',
    perNight: 'ijoro',
    perDay: 'umunsi',
    description: 'Ibisobanuro',
    amenities: 'Ibikoresho',
    features: 'Ibiranga',
    rules: 'Amategeko',
    ownerContact: 'Itumanaho ry\'umunyir\'ubwite',
    bookThis: 'Tuma iyi',
    startDate: 'Itariki yo Gutangira',
    endDate: 'Itariki yo Kurangiza',
    gender: 'Igitsina',
    maritalStatus: 'Irangamimerere',
    numberOfChildren: 'Umubare w\'abana',
    total: 'Igiteranyo',
    sendBookingRequest: 'Ohereza Icyifuzo cyo Gutuma',
    listingNotFound: 'Ikintu ntikibonetse',
    backToListings: 'Subira ku bintu',
    
    // Admin Dashboard
    adminDashboard: 'Ibikubiyemo by\'Umuyobozi',
    pendingReviews: 'Ibitegereje Gusuzumwa',
    verificationInfo: 'Amakuru yo Kwemeza',
    idNumber: 'Nimero y\'Indangamuntu',
    upiId: 'UPI ID',
    approveListing: 'Emeza Ikintu',
    rejectListing: 'Anga Ikintu',
    noPendingListings: 'Nta kintu gitegereje.',
    noApprovedListings: 'Nta kintu cyemewe.',
    noRejectedListings: 'Nta kintu cyanzwe.',
    owner: 'Umunyir\'ubwite',
    submitted: 'Cyatanzwe',
    pendingReview: 'Gitegereje Gusuzumwa',
    confirmReject: 'Emeza Kwanga',
    rejectionReason: 'Impamvu yo kwanga',
    
    // Alerts/Notifications
    areYouSure: 'Urabizi neza?',
    deleteListingConfirm: 'Uremeza ko ushaka gusiba iki kintu?',
    cancelBookingConfirm: 'Uremeza ko ushaka guhagarika gutuma?',
    blockUserConfirm: 'Hagarika uyu mukoresha? Azakenera kuvugana n\'umuyobozi kugirango agaruke.',
    unblockUserConfirm: 'Kureka guhagarika uyu mukoresha? Azagaruka mu buryo bwuzuye.',
    approveListingConfirm: 'Uremeza ko ushaka kwemeza iki kintu?',
    approveBookingConfirm: 'Emeza iki cyifuzo cyo gutuma?',
    rejectReasonPrompt: 'Tanga impamvu yo kwanga:',
    rejectReasonRequired: 'Tanga impamvu yo kwanga',
    emailAlreadyExists: 'Imeli yarakoreshejwe',
    invalidCredentials: 'Imeri cyangwa ijambo ry\'ibanga ntibikora',
    accountBlocked: 'Konti yawe yahagaritswe. Vugana n\'umuyobozi.',
    
    // Add Listing Form
    addNewListing: 'Andika Ikintu Gishya',
    propertyType: 'Ubwoko bw\'Umutungo',
    house: 'Inzu',
    car: 'Imodoka',
    title: 'Umutwe',
    titlePlaceholder: 'urugero: Apartama ifite ibyumba 2 i Kigali',
    descriptionPlaceholder: 'Sobanura umutungo wawe...',
    locationPlaceholder: 'Umujyi, Akarere',
    pricePerNight: 'Igiciro ku ijoro/umunsi',
    rentalPeriod: 'Igihe cyo Gukodesha',
    perDayOption: 'Ku Munsi',
    perMonthOption: 'Ku Kwezi',
    perYearOption: 'Ku Mwaka',
    selectRentalPeriod: 'Hitamo igihe ntarengwa cyo gukodesha umutungo wawe',
    photoUrl: 'URL y\'Ifoto',
    photoUrlPlaceholder: 'https://urugero.com/ifoto.jpg',
    orUploadPhotos: 'Cyangwa Ohereza Amafoto',
    uploadPhotos: 'Ohereza amafoto 5 y\'umutungo wawe',
    rulesPlaceholder: 'urugero: Nta kunywa itabi, Nta matungo...',
    verificationInfoDesc: 'Aya makuru aboneka gusa ku bayobozi kugirango bemeze.',
    idNumberPlaceholder: 'Nimero y\'indangamuntu yawe',
    upiIdPlaceholder: 'UPI ID yawe',
    agreeToTermsText: 'Nemera Amabwiriza n\'Amategeko kandi nemeza ko amakuru yose atanzwe ari ukuri. Ndumva ko amakuru atari ukuri ashobora gutera kwangwa no guhagarika konti.',
    submitting: 'Urimo kohereza...',
    submitForReview: 'Ohereza Kugirango Usuzumwe',
    required: 'birakenewe',
    
    // Admin Users Table
    userManagement: 'Kugenzura Abakoresha',
    totalUsers: 'Abakoresha Bose',
    activeUsers: 'Abakoresha Bakora',
    blockedUsers: 'Abakoresha Bahagaritswe',
    name: 'Izina',
    role: 'Uruhare',
    phone: 'Telefoni',
    actions: 'Ibikorwa',
    active: 'Irakora',
    blocked: 'Byahagaritswe',
    block: 'Hagarika',
    unblock: 'Kureka Guhagarika',
    admin: 'Umuyobozi',
    
    // User Profile
    myProfile: 'Umwirondoro Wanjye',
    uploadProfilePicture: 'Ohereza Ifoto y\'Umwirondoro',
    removeProfilePicture: 'Kuraho Ifoto y\'Umwirondoro',
    basicInformation: 'Amakuru y\'Ibanze',
    fullName: 'Amazina Yose',
    phoneNumber: 'Nimero ya Telefoni',
    changePassword: 'Hindura Ijambo ry\'Ibanga',
    leaveBlankPassword: 'Siga ubusa niba utashaka guhindura ijambo ry\'ibanga',
    currentPassword: 'Ijambo ry\'Ibanga Rikoreshwa',
    newPassword: 'Ijambo ry\'Ibanga Rishya',
    confirmNewPassword: 'Emeza Ijambo ry\'Ibanga Rishya',
    updating: 'Urimo guhindura...',
    updateProfile: 'Hindura Umwirondoro',
    profileUpdated: 'Umwirondoro wahindutse neza!',
    removeProfilePictureConfirm: 'Uremeza ko ushaka kuraho ifoto y\'umwirondoro?',
    
    // Admin Reports
    bookingReports: 'Raporo y\'Ibyakozwe',
    totalBookings: 'Ibyakozwe Byose',
    totalRevenue: 'Amafaranga Yose',
    listing: 'Ikintu',
    renter: 'Uwakodesha',
    dates: 'Amatariki',
    amount: 'Amafaranga',
  },
  
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    myBookings: 'Mes Réservations',
    bookingRequests: 'Demandes de Réservation',
    myListings: 'Mes Annonces',
    addListing: 'Ajouter une Annonce',
    profile: 'Profil',
    users: 'Utilisateurs',
    reports: 'Rapports',
    logout: 'Déconnexion',
    
    // Welcome Page
    welcomeTitle: 'Louez Maisons et Voitures – En Toute Sécurité',
    welcomeSubtitle: 'Connectez-vous avec des propriétaires de confiance. Chaque annonce est vérifiée pour votre sécurité.',
    iWantToRent: 'Je Veux Louer',
    iWantToList: 'Je Veux Publier',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    login: 'Se connecter',
    signup: 'S\'inscrire',
    signUp: 'S\'inscrire',
    forRenters: 'Pour les Locataires',
    forOwners: 'Pour les Propriétaires',
    howItWorks: 'Comment ça Marche',
    verifiedListings: 'Annonces vérifiées',
    transparentPricing: 'Prix transparents',
    easyBooking: 'Réservation facile',
    secureTransactions: 'Transactions sécurisées',
    earnFromAssets: 'Gagnez avec vos biens',
    simpleListing: 'Publication simple',
    adminVerification: 'Vérification admin',
    manageListings: 'Gérer les annonces',
    browseList: 'Parcourir/publier',
    bookSafely: 'Réserver en sécurité',
    
    // Auth & Signup
    email: 'Email',
    password: 'Mot de passe',
    name: 'Nom complet',
    phone: 'Numéro de téléphone',
    dontHaveAccount: 'Vous n\'avez pas de compte?',
    loggingIn: 'Connexion...',
    creatingAccount: 'Création du compte...',
    iWantTo: 'Je veux',
    rent: 'Louer (Locataire)',
    listAssets: 'Publier mes biens (Propriétaire)',
    verificationInfo: 'Informations de Vérification',
    verificationDesc: 'Pour la sécurité, tous les utilisateurs doivent fournir une vérification d\'identité.',
    nationalId: 'Carte d\'identité nationale ou Passeport',
    upiId: 'UPI ID / Compte bancaire (pour recevoir les paiements)',
    iAgreeToThe: 'J\'ai lu et j\'accepte les',
    termsAndConditions: 'Conditions Générales',
    iAccept: 'J\'accepte',
    minimumChars: 'Minimum 6 caractères',
    
    // Dashboard
    welcome: 'Bienvenue',
    browseListings: 'Parcourir les Annonces',
    browseAvailableListings: 'Parcourir les annonces disponibles ci-dessous',
    manageYourListings: 'Gérer vos annonces ci-dessous',
    noListingsFound: 'Aucune annonce trouvée.',
    noListingsYet: 'Vous n\'avez pas encore d\'annonces.',
    addFirstListing: 'Ajouter Votre Première Annonce',
    
    // Common
    search: 'Rechercher',
    type: 'Type',
    all: 'Tous',
    houses: 'Maisons',
    cars: 'Voitures',
    minPrice: 'Prix min',
    maxPrice: 'Prix max',
    price: 'Prix',
    location: 'Emplacement',
    status: 'Statut',
    pending: 'En attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    confirmed: 'Confirmé',
    cancelled: 'Annulé',
    submit: 'Soumettre',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    approve: 'Approuver',
    reject: 'Rejeter',
    save: 'Enregistrer',
    back: 'Retour',
    perNight: 'nuit',
    perDay: 'jour',
    description: 'Description',
    amenities: 'Équipements',
    features: 'Caractéristiques',
    rules: 'Règles',
    ownerContact: 'Contact Propriétaire',
    bookThis: 'Réserver ce',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    gender: 'Genre',
    maritalStatus: 'État Civil',
    numberOfChildren: 'Nombre d\'Enfants',
    total: 'Total',
    sendBookingRequest: 'Envoyer la Demande de Réservation',
    listingNotFound: 'Annonce non trouvée',
    backToListings: 'Retour aux annonces',
    
    // Admin Dashboard
    adminDashboard: 'Tableau de bord Admin',
    pendingReviews: 'En Attente de Révision',
    verificationInfo: 'Informations de Vérification',
    idNumber: 'Numéro d\'ID',
    upiId: 'UPI ID',
    approveListing: 'Approuver l\'Annonce',
    rejectListing: 'Rejeter l\'Annonce',
    noPendingListings: 'Aucune annonce en attente.',
    noApprovedListings: 'Aucune annonce approuvée.',
    noRejectedListings: 'Aucune annonce rejetée.',
    owner: 'Propriétaire',
    submitted: 'Soumis',
    pendingReview: 'En Attente de Révision',
    confirmReject: 'Confirmer le Rejet',
    rejectionReason: 'Raison du rejet',
    
    // Alerts/Notifications
    areYouSure: 'Êtes-vous sûr?',
    deleteListingConfirm: 'Êtes-vous sûr de vouloir supprimer cette annonce?',
    cancelBookingConfirm: 'Êtes-vous sûr de vouloir annuler cette réservation?',
    blockUserConfirm: 'Bloquer cet utilisateur? Il devra contacter l\'administrateur pour retrouver l\'accès.',
    unblockUserConfirm: 'Débloquer cet utilisateur? Il retrouvera un accès complet.',
    approveListingConfirm: 'Êtes-vous sûr de vouloir approuver cette annonce?',
    approveBookingConfirm: 'Approuver cette demande de réservation?',
    rejectReasonPrompt: 'Veuillez fournir une raison pour le rejet:',
    rejectReasonRequired: 'Veuillez fournir une raison pour le rejet',
    emailAlreadyExists: 'Cet email existe déjà',
    invalidCredentials: 'Email ou mot de passe invalide',
    accountBlocked: 'Votre compte a été bloqué. Veuillez contacter l\'administrateur.',
    
    // Add Listing Form
    addNewListing: 'Ajouter une Nouvelle Annonce',
    propertyType: 'Type de Propriété',
    house: 'Maison',
    car: 'Voiture',
    title: 'Titre',
    titlePlaceholder: 'ex: Appartement confortable de 2 chambres à Kigali',
    descriptionPlaceholder: 'Décrivez votre propriété...',
    locationPlaceholder: 'Ville, District',
    pricePerNight: 'Prix par nuit/jour',
    rentalPeriod: 'Période de Location',
    perDayOption: 'Par Jour',
    perMonthOption: 'Par Mois',
    perYearOption: 'Par An',
    selectRentalPeriod: 'Sélectionnez la période de location minimale pour votre propriété',
    photoUrl: 'URL de la Photo',
    photoUrlPlaceholder: 'https://exemple.com/photo.jpg',
    orUploadPhotos: 'Ou Télécharger des Photos',
    uploadPhotos: 'Téléchargez jusqu\'à 5 photos de votre propriété',
    rulesPlaceholder: 'ex: Pas de fumée, Pas d\'animaux...',
    verificationInfoDesc: 'Ces informations ne sont visibles que par les administrateurs à des fins de vérification.',
    idNumberPlaceholder: 'Votre numéro d\'ID',
    upiIdPlaceholder: 'Votre UPI ID',
    agreeToTermsText: 'J\'accepte les Conditions Générales et confirme que toutes les informations fournies sont exactes. Je comprends que de fausses informations peuvent entraîner le rejet de l\'annonce et la suspension du compte.',
    submitting: 'Envoi en cours...',
    submitForReview: 'Soumettre pour Révision',
    required: 'requis',
    
    // Admin Users Table
    userManagement: 'Gestion des Utilisateurs',
    totalUsers: 'Total des Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    blockedUsers: 'Utilisateurs Bloqués',
    name: 'Nom',
    role: 'Rôle',
    phone: 'Téléphone',
    actions: 'Actions',
    active: 'Actif',
    blocked: 'Bloqué',
    block: 'Bloquer',
    unblock: 'Débloquer',
    admin: 'Admin',
    
    // User Profile
    myProfile: 'Mon Profil',
    uploadProfilePicture: 'Télécharger Photo de Profil',
    removeProfilePicture: 'Supprimer Photo de Profil',
    basicInformation: 'Informations de Base',
    fullName: 'Nom Complet',
    phoneNumber: 'Numéro de Téléphone',
    changePassword: 'Changer le Mot de Passe',
    leaveBlankPassword: 'Laisser vide si vous ne voulez pas changer le mot de passe',
    currentPassword: 'Mot de Passe Actuel',
    newPassword: 'Nouveau Mot de Passe',
    confirmNewPassword: 'Confirmer le Nouveau Mot de Passe',
    updating: 'Mise à jour...',
    updateProfile: 'Mettre à Jour le Profil',
    profileUpdated: 'Profil mis à jour avec succès!',
    removeProfilePictureConfirm: 'Êtes-vous sûr de vouloir supprimer votre photo de profil?',
    
    // Admin Reports
    bookingReports: 'Rapports de Réservation',
    totalBookings: 'Total des Réservations',
    totalRevenue: 'Revenu Total',
    listing: 'Annonce',
    renter: 'Locataire',
    dates: 'Dates',
    amount: 'Montant',
  }
}

export function useLanguage() {
  const setLanguage = (lang) => {
    currentLanguage.value = lang
    localStorage.setItem('language', lang)
  }

  const t = (key) => {
    return translations[currentLanguage.value]?.[key] || translations.en[key] || key
  }

  return {
    currentLanguage: computed(() => currentLanguage.value),
    setLanguage,
    t
  }
}
